In [2]:
import numpy as np
np

<module 'numpy' from 'c:\\Development_Environments\\Conda\\envs\\GISAPI\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
#np.sin(np.array([1, 2, 3]))
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [6]:
type(arr[1])

numpy.int32

In [7]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = arr1.reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
arr2[2,0] = 10
arr2

array([[ 0,  1],
       [ 2,  3],
       [10, 10],
       [ 6,  7],
       [ 8,  9]])

In [16]:
arr2[:3]

array([[ 0,  1],
       [ 2,  3],
       [10, 10]])

In [17]:
arr2[(arr2> 3) & (arr2<6)]

array([], dtype=int32)

In [24]:
mat = np.arange(9).reshape((3,3))
vec = np.arange(3)

mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [27]:
test = np.array([1, 4, 9, 12])
test

array([ 1,  4,  9, 12])

In [30]:
test2 = test.reshape(2,2)
test2

array([[ 1,  4],
       [ 9, 12]])

In [31]:
test2.T

array([[ 1,  9],
       [ 4, 12]])

In [41]:
#test2.any()
test2[1,1]

12

In [43]:
test2.shape

(2, 2)

In [47]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
ones = np.ones([2,4])
ones.sum(axis=1)


array([4., 4.])

In [56]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
print(a)
a[2,4]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


14

In [69]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data.max(axis=1)

array([2, 4, 6])

In [71]:
rng = np.random.default_rng()
numbs = rng.integers(20, size=(3,4))
np.unique(numbs)

array([ 0,  3,  7,  8,  9, 10, 12, 18], dtype=int64)

In [9]:
import os
import tarfile
import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

In [10]:
fetch_housing_data()

HTTPError: HTTP Error 404: Not Found

In [6]:
import pandas as pd

def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)


load_housing_data()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
